// <auto-generated />
using System;
using MicroService.Users.Data.DataContext.Impl;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MicroService.Users.Product.APIs.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("product")
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MicroService.Users.Data.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("f1d035d6-ab42-45a7-9eca-b6d8f62a6ad3"),
                            ProductName = "Samsung Galaxy s20",
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = new Guid("db12837b-acd8-489d-aaa0-88afba3aaac4"),
                            ProductName = "Samsung Galaxy s10",
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = new Guid("fe1ce873-e25c-4d4c-a0a4-1cee847947a1"),
                            ProductName = "Samsung Galaxy Note 10+",
                            Quantity = 15
                        },
                        new
                        {
                            ProductId = new Guid("7900152b-8c9d-4fb0-8982-85374984f9bb"),
                            ProductName = "Samsung Galaxy Note 9+",
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = new Guid("5d81e588-e9e5-48f3-af8a-4f9f2f8ba4e7"),
                            ProductName = "OnePlus7T prp",
                            Quantity = 15
                        });
                });

            modelBuilder.Entity("MicroService.Users.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
